### PR TITLE
Use qiskit test providers 52

### PR DESCRIPTION
**Pull request by jwoehr**
### Summary

Address #52 

### Details and comments

This is a start. The rebases are not ideal for the intended purpose. I have taken one approach. You may wish to  provide guidance for more work on this.

### CODE REVIEW

**Comment by jwoehr** [comment]
This is failing because I have created a new directory. Not sure how to make that work with a pull request.

**Comment by diego-plan9** [comment]
Thanks @jwoehr !

> This is failing because I have created a new directory. Not sure how to make that work with a pull request.

Can you try placing the files currently at:
```
/qiskit/test/providers/ibmq/
```
inside `/test/ibmq` (both paths on the comment referring to the root dir of the repo)? The way it is currently (as of a5f2230) it will cause a clash between module names.

Also, don't worry too much about rebasing, etc - we can reconcile back with `master` when the PR is ready!

**Comment by jwoehr** [comment]
Whee! It passes.

**Comment by diego-plan9** [comment]
Thanks for the patience, @jwoehr! Just a comment to let you know the PR did not go unnoticed - the "rush period" has arrived and is requiring quite a lot of energy, but we will review this PR once things quiet down a bit (hopefully later this week).

**Comment by jwoehr** [comment]
> Thanks for the patience, @jwoehr! Just a comment to let you know the PR did not go unnoticed -

No problem. You might want some changes on this, so I look forward to your review.

**Comment by jwoehr** [comment]
Merged #52 with the accepted code from #53

**Comment by jwoehr** [comment]
Odd, there see to be three checks now, and all have fully passed, but it thinks one is not complete.

**Comment by diego-plan9** [comment]
Apologies for taking longer than usual to provide feedback, @jwoehr ! As you might have guessed by the number of issues and PRs created on the repo, we are in the midst of a quite high-activity period in different fronts, but finally managed the time to take a deeper look at your PR.

If I'm reading it right (thanks for the detailed comments in the new files!), most of the effort comes from trying to solve the "dynamically create and run a `BackendTestCase` for the discovered backends", which indeed is not well supported at the moment due to the nature of this particular provider (as in, you don't know what backends exists until the provider is instantiated, which is more complex that local providers).

I think the solution you achieved is quite creative, although it unfortunately has some inconvenient side effects. They are mostly derived from the `test_backends_IBMQBackendTestCase` implementation, combined with the way the Python test framework is structured:

```
        for backend in self.provider.backends():
            TextTestRunner(verbosity=2).run(
                TestLoader().loadTestsFromTestCase(self.gen_backend_test_class(backend))
            )
```

Usually creating a `TestRunner` is responsability of the user (as in, the user will launch the tests through a tool, which can be `python -m unittest` or other, such as the IDE unittest launcher, `pytest`, etc): a `SomethingTestRunner` is created, which then compiles the test suite, runs the individual tests, etc. These lines potentially make a new test runner to be created when running a test from the original test runner used by the user, which can have a number of oddities in the flow (for example, I ended up having all the tests for a backend as a _single_ pytest test with `unittest` output while running the full suite with `pytest`, and was unable to run the test individually with the Pycharm stock runner).

We will probably be able to take some ideas from your approach (such as customizing the loading, or seeing if we can move the dynamic loading under a more controlled layer), but it will probably require some exploratory effort - and I'm thinking a more sensible approach would be to split the PR in parts, so we can advance in each front individually.

What I'm proposing, re-reading #52, is:
* make a PR that only deals with making use of `ProviderTestCase`. Hopefully this will be quite tiny and quick to review and merge.
* follow up with another PR that evaluates with making use of `BackendTestCase`, and in turn deal with the dynamic nature of the backends. This one would actually not be high priority - more of a "wishlist" of sorts.

Would it make sense? Thanks for the effort put into the issue, which turned out to be a bit more tricky than expected!

**Comment by diego-plan9** [comment]
On a minor note ...

> Odd, there see to be three checks now, and all have fully passed, but it thinks one is not complete.

Yes, we had a small hiccup with travis during the time your last merge commit was made - the next one will hopefully have the usual two checks instead of three.

**Comment by jwoehr** [comment]
> Apologies for taking longer than usual to provide feedback, @jwoehr !

No problem, we're all keeping busy :)

> (thanks for the detailed comments in the new files!)

You're welcome.

> Usually creating a `TestRunner` is responsability of the user

Yes, I couldn't figure out how to simply chain the dynamically generated test entity to the calling test entity. Spent some hours reading the Python docs for `unittest` but did not succeed in untangling!



> What I'm proposing, re-reading #52, is:
> 
>     * make a PR that only deals with making use of `ProviderTestCase`. Hopefully this will be quite tiny and quick to review and merge.
> 
>     * follow up with another PR that evaluates with making use of `BackendTestCase`, and in turn deal with the dynamic nature of the backends. This one would actually not be high priority - more of a "wishlist" of sorts.

> Would it make sense? Thanks for the effort put into the issue, which turned out to be a bit more tricky than expected!

Yes this makes sense. Change the issue and I'll work on it.

**Comment by jwoehr** [comment]
> On a minor note ...
> 
> > Odd, there see to be three checks now, and all have fully passed, but it thinks one is not complete.
> 
> Yes, we had a small hiccup with travis during the time your last merge commit was made - the next one will hopefully have the usual two checks instead of three.

Okay, so I was not hallucinating :)

**Comment by jwoehr** [comment]
Closed in view of revised #52

**Pull request closed without merging**
