### PR TITLE
New IBM Q Experience site instructions

### PR DESCRIPTION
**Pull request by jwoehr**
### Summary
Issue #168 .. revise README.md

### Details and comments
Change URLs and instructions.

### CODE REVIEW

**Comment by diego-plan9** [comment]
Thanks @jwoehr ! Can you fix the conflicts, as #152 was merged (they are probably just the links)?

**Comment by jwoehr** [comment]
I think it's all fixed.

**Comment by diego-plan9** [comment]
Thanks @jwoehr ! It's looking good, although we will wait a bit before merging in order to mark the start of the "official" support of the new API.

**Comment by diego-plan9** [comment]
Let's kick things off!

**Pull request merged**
